name: waste_not_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.9.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.3.0
  firebase_core: ^2.30.1      
  firebase_auth: ^4.17.6       
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ‚¨ÖÔ∏è added for app icon

flutter:
  uses-material-design: true

  assets:
    - assets/Images/home_slide1.png
    - assets/Images/home_slide2.png
    - assets/Images/home_slide3.png
    - assets/Images/home_slide4.png
    - assets/Images/food_donatation.png
    - assets/Images/book_donatation.png
    - assets/Images/cloth_donatation.png
    - assets/Images/special_days.png
    - assets/Images/customer-service.png
    - assets/Images/upcoming_event.png
    - assets/Images/featurede_ngo.png
    - assets/Images/bell.png
    - assets/Images/feedback.png
    - assets/Images/heart.png
    - assets/Images/key.png
    - assets/Images/logout.png
    - assets/Images/setting.png
    - assets/Images/support.png
    - assets/Images/book.png
    - assets/Images/books.png
    - assets/Images/calendar.png
    - assets/Images/clothes.png
    - assets/Images/food.png
    - assets/Images/location.png
    - assets/Images/notes.png
    - assets/Images/phone.png
    - assets/Images/quantity.png
    - assets/Images/sharing.png
    - assets/Images/time.png
    - assets/Images/upload.png
    - assets/Images/avatar.png
    - assets/Images/featured_ngo1.png
    - assets/Images/featured_ngo2.png
    - assets/Images/featured_ngo3.png
    - assets/Images/guidelines.png
    - assets/Images/google.png
    - assets/Images/logo.png
    - assets/Images/charity1.png
    - assets/Images/fooddonation1.png
    - assets/Images/bookgiving1.png
    - assets/Images/clothdonation1.png
    - assets/Images/hunger1.png
    - assets/Images/kindness1.png
    - assets/Images/sharing1.png
    - assets/Images/volunteer1.png
    - assets/Images/book1.png
    - assets/Images/earth1.png
    - assets/Images/calendar2.png

# üîπ Flutter Launcher Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/Images/logo.png   # change if you want another icon
